async function generatePDF()
{
    var doc = new jsPDF("portrait", "mm", "letter");
    var date = new Date();

    // HEADER
    doc.setFont("times", "bold");
    doc.setFontSize(16);
    doc.text(72, 20, 'IRACE Autogenerated report');

    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.text(20, 40, 'Date of the report: ' + date);

    // SUMMARY
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text(20, 55, 'Summary')
    doc.line(19, 56, 42, 56);
    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.autoTable({
        startY: 60,
        html: '#tablaSummary1',
        styles: {overflow: 'hidden'},
        margin: {right: 125},
        theme: 'plain'
    });
    doc.autoTable({
        startY: 60,
        html: '#tablaSummary2',
        styles: {overflow: 'hidden'},
        margin: {left: 125},
        theme: 'plain'
    });

    // BEST CONFIGURATION
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text(20, 130, 'Best Configuration')
    doc.line(19, 131, 63, 131);
    doc.setFont("times", "normal");
    doc.setFontSize(9);
    source = $('#boxPlotBestConfiguration').children('img')[0].src;

    await loadImage(source).then(formatedImage =>{
        doc.addImage(formatedImage, 119, 140, 60, 70);
        console.log('Add image: Boxplot best-configuration')
    })

    var bestConfiguration = formatBestConfiguration();
    var yLine = 140;
    var pageHeight = 257;
    for(i = 0; i < bestConfiguration.length; i++)
    {
        doc.text(20, yLine, bestConfiguration[i])
        if(i >= 20 && i < (bestConfiguration.length-1))
        {
            doc.text(125, yLine, bestConfiguration[i+1]);
            i++;
        }
        yLine += 4
        if(pageHeight <=  yLine)
        {
            doc.setFont("times", "bold");
            doc.setFontSize(16);
            doc.text(72, 20, 'IRACE Autogenerated report');
            doc.setFont("times", "normal");
            doc.setFontSize(9);
            yLine = 30;
            pageHeight = 265;
            doc.addPage();
            doc.setPage(doc.internal.getNumberOfPages());
        }
    }

    // CANDIDATES
    doc.addPage();
    doc.setPage(doc.internal.getNumberOfPages());
    doc.setFont("times", "bold");
    doc.setFontSize(16);
    doc.text(72, 20, 'IRACE Autogenerated report');

    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text(20, 35, 'Candidates')
    doc.line(19, 36, 55, 36);
    doc.setFontSize(11);
    doc.text(20, 40, 'Last two iterations')
    doc.setFont("times", "bold");
    doc.setFontSize(9);
    doc.text(50, 50, 'Frequency Plots')
    doc.text(142, 50, 'Parallel Coordinates Plots')

    var iterations = [8, 9];
    Shiny.onInputChange("requestPlottingCandidates", iterations);
    await waitForData(1).then(async plots =>{
        var yLine = 55;
        var imgHeight = 95;
        var pageHeight = 257;
        if(plots['frequency'][0].length == 1 || plots['parallel'][0].length == 1)
        {
            await loadImage(plots['frequency']).then(formatedImage =>{
                doc.addImage(formatedImage, 15, yLine, 90, 90);
                console.log("Add image: Frequency plot " + plots['frequency'][0].length)
            })
            await loadImage(plots['parallel']).then(formatedImage =>{
                doc.addImage(formatedImage, 115, yLine, 90, 70);
                console.log("Add image: Parallel Coordinates plot " + plots['parallel'][0].length)
            })
        }
        else
        {
            var maxPlotting = plots['parallel'].length;
            var newPage = true;
            console.log('Amount of Parallel Coordinates Plots: ' + plots['parallel'].length)
            console.log('Amount of Frequency Plots: ' + plots['frequency'].length)
            if(plots['frequency'].length > plots['parallel'].length)
                maxPlotting = plots['frequency'].length
            for(i = 0; i < maxPlotting; i++)
            {
                if(maxPlotting <= plots['frequency'].length)
                    await loadImage(plots['frequency'][i]).then(formatedImage =>{
                        doc.addImage(formatedImage, 15, yLine, 95, 95);
                        console.log("Add image: Frequency plot " + (i + 1))
                    });
                if(maxPlotting <= plots['parallel'].length)
                {
                    yLineParallel = yLine;
                    if(i != 0 && !newPage)
                        yLineParallel -= 20
                    newPage = false;
                    await loadImage(plots['parallel'][i]).then(formatedImage =>{
                        doc.addImage(formatedImage, 115, yLineParallel, 90, 70);
                        console.log("Add image: Parallel Coordinates plot " + (i + 1))
                    });
                }
                yLine += (imgHeight + 1);
                if(pageHeight <=  (yLine + imgHeight))
                {
                    doc.setFont("times", "bold");
                    doc.setFontSize(16);
                    doc.text(72, 20, 'IRACE Autogenerated report');
                    doc.setFont("times", "normal");
                    doc.setFontSize(9);
                    yLine = 30;
                    newPage = true;
                    pageHeight = 265;
                    doc.addPage();
                    doc.setPage(doc.internal.getNumberOfPages());
                }
            }
        }
    })

    // PERFOMANCE
    doc.addPage();
    doc.setPage(doc.internal.getNumberOfPages());
    doc.setFont("times", "bold");
    doc.setFontSize(16);
    doc.text(72, 20, 'IRACE Autogenerated report');

    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text(20, 35, 'Perfomance')
    doc.line(19, 36, 48, 36);
    doc.setFontSize(11);
    doc.text(20, 40, 'Last iteration')
    doc.setFont("times", "bold");
    doc.setFontSize(9);
    doc.text(50, 50, 'Convergence Plot')
    doc.text(46, 53, '(Valid for all iterations)')
    doc.text(142, 50, 'BoxPlot elite configurations')

    source = $('#convergencePerfomance').children('img')[0].src;

    await loadImage(source).then(formatedImage =>{
        doc.addImage(formatedImage, 20, 54, 80, 80);
        console.log('Add image: Convergence plot')
    });

    var iteration = 9;
    Shiny.onInputChange("requestPlottingPerfomance", iteration);
    await waitForData(2).then(async plot =>{
        await loadImage(plot['boxPlot']).then(formatedImage =>{
            doc.addImage(formatedImage, 100, 53, 100, 130);
            console.log('Add image: Boxplot Perfomance')
        });
    });

    // DETAILS
    doc.addPage();
    doc.setPage(doc.internal.getNumberOfPages());
    doc.setFont("times", "bold");
    doc.setFontSize(16);
    doc.text(72, 20, 'IRACE Autogenerated report');

    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text(20, 35, 'Details by iteration')
    doc.line(19, 36, 63, 36);
    doc.setFontSize(11);
    doc.text(20, 40, 'Best-so-far of each iteration')
    doc.setFont("times", "bold");
    doc.setFontSize(9);
    doc.setFont("times", "normal");

    Shiny.onInputChange("requestBestSoFarIterations", true);
    await waitForData(3).then(async valuesTable =>{
        var yLine = 50;
        var pageHeight = 265;
        for(i = 1; i < valuesTable.length; i++)
        {
            doc.setFontSize(9);
            if(yLine != 25)
                yLine += 10
            doc.setFont("times", "bold");
            doc.text(20, yLine, ('Iteration ' + i))
            yLine += 5
            doc.setFont("times", "normal");
            doc.text(20, yLine, ('Best-so-far configuration: ' + valuesTable[i]['id']))
            yLine += 4
            doc.text(20, yLine, 'mean value: ' + valuesTable[i]['mean'])
            yLine += 6
            /*
            var data = formatParams(valuesTable[0], valuesTable[i]['paramData']);
            for(var j = 0; j < data.length; j++)
            {
                doc.autoTable({
                    startY: yLine,
                    head: [
                        data[j][0]
                    ],
                    body: [
                        data[j][1]
                    ],
                    margin: {right: 15,
                            left: 15},
                    theme: 'grid'
                });
                yLine += 30
            }
            */
            doc.setFontSize(6);
            var width = doc.getTextWidth('ID: ');
            doc.setFont("times", "bold");
            doc.text(20, yLine, 'ID: ')
            doc.setFont("times", "normal");
            doc.text(20 + width + 2, yLine, '' + valuesTable[i]['paramData']['.ID.'][0])
            
            var width = doc.getTextWidth('PARENT: ');
            doc.setFont("times", "bold");
            doc.text(85, yLine, 'PARENT: ')
            doc.setFont("times", "normal");

            if(valuesTable[i]['paramData']['.PARENT.'][0] == null)
                doc.text(85 + width + 2, yLine, 'NA')
            else
                doc.text(85 + width + 2, yLine, '' + valuesTable[i]['paramData']['.PARENT.'][0])

            yLine += 3
            for(var j = 0; j < valuesTable[0].length; j++)
            {
                var width = doc.getTextWidth(valuesTable[0][j]);
                doc.setFont("times", "bold");
                doc.text(20, yLine, valuesTable[0][j] + ':')
                doc.setFont("times", "normal");
                if(valuesTable[i]['paramData'][valuesTable[0][j]][0] == null)
                    doc.text(20 + width + 2, yLine, 'NA')
                else
                    doc.text(20 + width + 2, yLine, '' + valuesTable[i]['paramData'][valuesTable[0][j]][0])

                if(valuesTable[0][j + 1] != undefined)
                {
                    var width = doc.getTextWidth(valuesTable[0][j + 1]);
                    doc.setFont("times", "bold");
                    doc.text(85, yLine, valuesTable[0][j + 1] + ': ')
                    doc.setFont("times", "normal");

                    if(valuesTable[i]['paramData'][valuesTable[0][j + 1]][0] == null)
                        doc.text(85 + width + 2, yLine, 'NA')
                    else
                        doc.text(85 + width + 2, yLine, "" + valuesTable[i]['paramData'][valuesTable[0][j + 1]][0])
                    j++;
                }

                if(valuesTable[0][j + 1] != undefined)
                {
                    var width = doc.getTextWidth(valuesTable[0][j + 1]);
                    doc.setFont("times", "bold");
                    doc.text(150, yLine, valuesTable[0][j + 1] + ': ')
                    doc.setFont("times", "normal");

                    if(valuesTable[i]['paramData'][valuesTable[0][j + 1]][0] == null)
                        doc.text(150 + width + 2, yLine, 'NA')
                    else
                        doc.text(150 + width + 2, yLine, "" + valuesTable[i]['paramData'][valuesTable[0][j + 1]][0])
                    j++;
                }

                yLine += 3
                if(pageHeight <  (yLine + 20))
                {
                    doc.setFont("times", "bold");
                    doc.setFontSize(16);
                    doc.text(72, 20, 'IRACE Autogenerated report');
                    doc.setFont("times", "normal");
                    doc.setFontSize(6);
                    yLine = 35;
                    pageHeight = 265;
                    doc.addPage();
                    doc.setPage(doc.internal.getNumberOfPages());
                }
            }
        }
    });

    doc.setProperties({
        title: 'IRACE Report',	
        author: 'IRACE-GUI',
        creator: 'IRACE-GUI'
    });

    console.log('Save PDF');
    doc.save('IRACE' + date.getTime() + '.pdf');
}

function formatBestConfiguration()
{
    var data = document.getElementById('bestConfigurationsDetails').innerHTML.replace(/<[^>]*>/g, "\n").replace(/♛|➔/g, "").split('\n');
    var formatedData = [];
    var index = 0;
    for(i = 0; i < data.length; i++)
        if(data[i] != "")
        {
            formatedData[index] = data[i];
            index++
        }
    return formatedData;
}

function loadImage(src)
{
    return new Promise((resolve, reject) => {
        console.log('Rendering in 1080p resolution...')
        let img = new Image(),
            canvas = document.createElement("canvas"),
            ctx = canvas.getContext("2d");
            // upscale the canvas content
            canvas.width = 1920 * devicePixelRatio;
            canvas.height = 1080 * devicePixelRatio;
            // downscale the presentation
            canvas.style.width = (canvas.width / devicePixelRatio).toString() + "px";
            canvas.style.height = (canvas.height / devicePixelRatio).toString() + "px";
        img.onload = () => {
            ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
            var imgData = canvas.toDataURL('image/jpeg');
            resolve(imgData)
        }
        img.onerror = reject
        img.src = src
    })
}

function formatParams(params, values)
{
    var max = 5;
    var arrayMax = [];
    var maxParamsArray = [];

    var arrayParams = [];
    var arrayValues = [];

    var k = 0;
    var index = 0;

    for(var j = 0; j < params.length; j++)
    {
        if(k >= max)
        {
            arrayParams[0] = "ID";
            arrayValues[0] = values['.ID.'];

            arrayParams[max + 1] = "PARENT";
            if(values['.PARENT.'][0] == null)
                arrayValues[max + 1] = "NA";
            else
                arrayValues[max + 1] = values['.PARENT.'][0];

            arrayMax[0] = arrayParams;
            arrayMax[1] = arrayValues;

            console.log(arrayParams)

            maxParamsArray[index] = arrayMax;
            index++;
            k = 0;
        }
        arrayParams[k + 1] = params[j];
        if(values[params[j]][0] == null)
            arrayValues[k + 1] = "NA"
        else
            arrayValues[k + 1] = values[params[j]][0]
        k++;
    }

    return maxParamsArray;
}

function waitForData(required)
{
    if(required == 1)
        return new Promise((resolve, reject) => {
            Shiny.addCustomMessageHandler('imagePlotCandidates', 
                function(params) 
                {
                    resolve(params)
                });
        });
    if(required == 2)
        return new Promise((resolve, reject) => {
            Shiny.addCustomMessageHandler('imagePlotPerfomance', 
                function(params) 
                {
                    resolve(params)
                });
        });
    if(required == 3)
        return new Promise((resolve, reject) => {
            Shiny.addCustomMessageHandler('bestSoFarAllIterations', 
                function(params) 
                {
                    resolve(params)
                });
        });
}